Recommendation systems are a collection of algorithms used to recommend items to users based on information taken from the user. These systems have become ubiquitous can be commonly seen in online stores, movies databases and job finders. In this notebook, we will explore recommendation systems based on Collaborative Filtering and implement simple version of one using Python and the Pandas library.

<a id="ref1"></a>

# Acquiring the Data

In [3]:
!wget -O moviedataset.zip https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/ML0101ENv3/labs/moviedataset.zip
print('unziping ...')
!unzip -o -j moviedataset.zip

--2020-10-25 13:35:04--  https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/ML0101ENv3/labs/moviedataset.zip
Resolving s3-api.us-geo.objectstorage.softlayer.net (s3-api.us-geo.objectstorage.softlayer.net)... 67.228.254.196
Connecting to s3-api.us-geo.objectstorage.softlayer.net (s3-api.us-geo.objectstorage.softlayer.net)|67.228.254.196|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 160301210 (153M) [application/zip]
Saving to: ‘moviedataset.zip’

moviedataset.zip    100%[===================>] 152.88M  24.9MB/s    in 6.7s

2020-10-25 13:35:11 (22.7 MB/s) - ‘moviedataset.zip’ saved [160301210/160301210]

unziping ...
Archive:  moviedataset.zip
  inflating: links.csv
  inflating: movies.csv
  inflating: ratings.csv
  inflating: README.txt
  inflating: tags.csv

Now you're ready to start working with the data!

<hr>

<a id="ref2"></a>

# Preprocessing

In [5]:
#Dataframe manipulation library
import pandas as pd
#Math functions, we'll only need the sqrt function so let's import only that
from math import sqrt
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

Now let's read each file into their Dataframes:

In [6]:
#Storing the movie information into a pandas dataframe
movies_df = pd.read_csv('movies.csv')
#Storing the user information into a pandas dataframe
ratings_df = pd.read_csv('ratings.csv')

# Let's also take a peek at how each of them are organized:

In [7]:
#Head is a function that gets the first N rows of a dataframe. N's default is 5.
movies_df.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

So each movie has a unique ID, a title with its release year along with it (Which may contain unicode characters) and several different genres in the same field. Let's remove the year from the title column and place it into its own one by using the handy [extract](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.str.extract.html#pandas.Series.str.extract?cm_mmc=Email_Newsletter-_-Developer_Ed%2BTech-_-WW_WW-_-SkillsNetwork-Courses-IBMDeveloperSkillsNetwork-ML0101EN-SkillsNetwork-20718538&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ&cm_mmc=Email_Newsletter-_-Developer_Ed%2BTech-_-WW_WW-_-SkillsNetwork-Courses-IBMDeveloperSkillsNetwork-ML0101EN-SkillsNetwork-20718538&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ) function that Pandas has.

Let's remove the year from the **title** column by using pandas' replace function and store in a new **year** column.

In [8]:
#Using regular expressions to find a year stored between parentheses
#We specify the parantheses so we don't conflict with movies that have years in their titles
movies_df['year'] = movies_df.title.str.extract('(\(\d\d\d\d\))',expand=False)
#Removing the parentheses
movies_df['year'] = movies_df.year.str.extract('(\d\d\d\d)',expand=False)
#Removing the years from the 'title' column
movies_df['title'] = movies_df.title.str.replace('(\(\d\d\d\d\))', '')
#Applying the strip function to get rid of any ending whitespace characters that may have appeared
movies_df['title'] = movies_df['title'].apply(lambda x: x.strip())

Let's look at the result!

In [9]:
movies_df.head()

,movieId,title,genres,year
0,1,Toy Story,Adventure|Animation|Children|Comedy|Fantasy,1995
1,2,Jumanji,Adventure|Children|Fantasy,1995
2,3,Grumpier Old Men,Comedy|Romance,1995
3,4,Waiting to Exhale,Comedy|Drama|Romance,1995
4,5,Father of the Bride Part II,Comedy,1995

With that, let's also drop the genres column since we won't need it for this particular recommendation system.

In [10]:
#Dropping the genres column
movies_df = movies_df.drop('genres', 1)

Here's the final movies dataframe:

In [11]:
movies_df.head()

   movieId                        title  year
0        1                    Toy Story  1995
1        2                      Jumanji  1995
2        3             Grumpier Old Men  1995
3        4            Waiting to Exhale  1995
4        5  Father of the Bride Part II  1995

<br>

Next, let's look at the ratings dataframe.

In [12]:
ratings_df.head()

   userId  movieId  rating   timestamp
0       1      169     2.5  1204927694
1       1     2471     3.0  1204927438
2       1    48516     5.0  1204927435
3       2     2571     3.5  1436165433
4       2   109487     4.0  1436165496

Every row in the ratings dataframe has a user id associated with at least one movie, a rating and a timestamp showing when they reviewed it. We won't be needing the timestamp column, so let's drop it to save on memory.

In [13]:
#Drop removes a specified row or column from a dataframe
ratings_df = ratings_df.drop('timestamp', 1)

Here's how the final ratings Dataframe looks like:

In [14]:
ratings_df.head()

   userId  movieId  rating
0       1      169     2.5
1       1     2471     3.0
2       1    48516     5.0
3       2     2571     3.5
4       2   109487     4.0

<hr>

<a id="ref3"></a>

# Collaborative Filtering

In [15]:
userInput = [
            {'title':'Breakfast Club, The', 'rating':5},
            {'title':'Toy Story', 'rating':3.5},
            {'title':'Jumanji', 'rating':2},
            {'title':"Pulp Fiction", 'rating':5},
            {'title':'Akira', 'rating':4.5}
         ] 
inputMovies = pd.DataFrame(userInput)
inputMovies

                 title  rating
0  Breakfast Club, The     5.0
1            Toy Story     3.5
2              Jumanji     2.0
3         Pulp Fiction     5.0
4                Akira     4.5

#### Add movieId to input user

With the input complete, let's extract the input movies's ID's from the movies dataframe and add them into it.

We can achieve this by first filtering out the rows that contain the input movies' title and then merging this subset with the input dataframe. We also drop unnecessary columns for the input to save memory space.

In [16]:
#Filtering out the movies by title
inputId = movies_df[movies_df['title'].isin(inputMovies['title'].tolist())]
#Then merging it so we can get the movieId. It's implicitly merging it by title.
inputMovies = pd.merge(inputId, inputMovies)
#Dropping information we won't use from the input dataframe
inputMovies = inputMovies.drop('year', 1)
#Final input dataframe
#If a movie you added in above isn't here, then it might not be in the original 
#dataframe or it might spelled differently, please check capitalisation.
inputMovies

   movieId                title  rating
0        1            Toy Story     3.5
1        2              Jumanji     2.0
2      296         Pulp Fiction     5.0
3     1274                Akira     4.5
4     1968  Breakfast Club, The     5.0

In [17]:
ratings_df.head()

   userId  movieId  rating
0       1      169     2.5
1       1     2471     3.0
2       1    48516     5.0
3       2     2571     3.5
4       2   109487     4.0

#### The users who has seen the same movies

Now with the movie ID's in our input, we can now get the subset of users that have watched and reviewed the movies in our input.

In [18]:
#Filtering out users that have watched movies that the input has watched and storing it
userSubset = ratings_df[ratings_df['movieId'].isin(inputMovies['movieId'].tolist())]
userSubset.head()

     userId  movieId  rating
19        4      296     4.0
441      12     1968     3.0
479      13        2     2.0
531      13     1274     5.0
681      14      296     2.0

We now group up the rows by user ID.

In [41]:
#Groupby creates several sub dataframes where they all have the same value in the column specified as the parameter
userSubsetGroup = userSubset.groupby(['userId'])

lets look at one of the users, e.g. the one with userID=1130

In [42]:
userSubsetGroup.get_group(1130)

        userId  movieId  rating
104167    1130        1     0.5
104168    1130        2     4.0
104214    1130      296     4.0
104363    1130     1274     4.5
104443    1130     1968     4.5

Let's also sort these groups so the users that share the most movies in common with the input have higher priority. This provides a richer recommendation since we won't go through every single user.

In [43]:
#Sorting it so users with movie most in common with the input will have priority
userSubsetGroup = sorted(userSubsetGroup,  key=lambda x: len(x[1]), reverse=True)

Now lets look at the first user

In [44]:
userSubsetGroup[0:4]

[(75,
        userId  movieId  rating
  7507      75        1     5.0
  7508      75        2     3.5
  7540      75      296     5.0
  7633      75     1274     4.5
  7673      75     1968     5.0),
 (106,
        userId  movieId  rating
  9083     106        1     2.5
  9084     106        2     3.0
  9115     106      296     3.5
  9198     106     1274     3.0
  9238     106     1968     3.5),
 (686,
         userId  movieId  rating
  61336     686        1     4.0
  61337     686        2     3.0
  61377     686      296     4.0
  61478     686     1274     4.0
  61569     686     1968     5.0),
 (815,
         userId  movieId  rating
  73747     815        1     4.5
  73748     815        2     3.0
  73922     815      296     5.0
  74362     815     1274     3.0
  74678     815     1968     4.5)]

We will select a subset of users to iterate through. This limit is imposed because we don't want to waste too much time going through every single user.

In [45]:
userSubsetGroup = userSubsetGroup[0:100]

Now, we calculate the Pearson Correlation between input user and subset group, and store it in a dictionary, where the key is the user Id and the value is the coefficient

In [65]:
#Store the Pearson Correlation in a dictionary, where the key is the user Id and the value is the coefficient
pearsonCorrelationDict = {}

#For every user group in our subset
for name, group in userSubsetGroup:
    #Let's start by sorting the input and current user group so the values aren't mixed up later on
    group = group.sort_values(by='movieId')
    print(name,'+', group)
    inputMovies = inputMovies.sort_values(by='movieId')
    print(inputMovies)
    #Get the N for the formula
    nRatings = len(group)
    print('++++',nRatings)
    #Get the review scores for the movies that they both have in common
    temp_df = inputMovies[inputMovies['movieId'].isin(group['movieId'].tolist())]
    #And then store them in a temporary buffer variable in a list format to facilitate future calculations
    tempRatingList = temp_df['rating'].tolist()
    print(tempRatingList)
    #Let's also put the current user group reviews in a list format
    tempGroupList = group['rating'].tolist()
    print(tempGroupList)
    #Now let's calculate the pearson correlation between two users, so called, x and y
    Sxx = sum([i**2 for i in tempRatingList]) - pow(sum(tempRatingList),2)/float(nRatings)
    Syy = sum([i**2 for i in tempGroupList]) - pow(sum(tempGroupList),2)/float(nRatings)
    Sxy = sum( i*j for i, j in zip(tempRatingList, tempGroupList)) - sum(tempRatingList)*sum(tempGroupList)/float(nRatings)
    
    #If the denominator is different than zero, then divide, else, 0 correlation.
    if Sxx != 0 and Syy != 0:
        pearsonCorrelationDict[name] = Sxy/sqrt(Sxx*Syy)
    else:
        pearsonCorrelationDict[name] = 0

75 +       userId  movieId  rating
7507      75        1     5.0
7508      75        2     3.5
7540      75      296     5.0
7633      75     1274     4.5
7673      75     1968     5.0
   movieId                title  rating
0        1            Toy Story     3.5
1        2              Jumanji     2.0
2      296         Pulp Fiction     5.0
3     1274                Akira     4.5
4     1968  Breakfast Club, The     5.0
++++ 5
[3.5, 2.0, 5.0, 4.5, 5.0]
[5.0, 3.5, 5.0, 4.5, 5.0]
106 +       userId  movieId  rating
9083     106        1     2.5
9084     106        2     3.0
9115     106      296     3.5
9198     106     1274     3.0
9238     106     1968     3.5
   movieId                title  rating
0        1            Toy Story     3.5
1        2              Jumanji     2.0
2      296         Pulp Fiction     5.0
3     1274                Akira     4.5
4     1968  Breakfast Club, The     5.0
++++ 5
[3.5, 2.0, 5.0, 4.5, 5.0]
[2.5, 3.0, 3.5, 3.0, 3.5]
686 +        userId  movieId  rating
61336     686        1     4.0
61337     686        2     3.0
61377     686      296     4.0
61478     686     1274     4.0
61569     686     1968     5.0
   movieId                title  rating
0        1            Toy Story     3.5
1        2              Jumanji     2.0
2      296         Pulp Fiction     5.0
3     1274                Akira     4.5
4     1968  Breakfast Club, The     5.0
++++ 5
[3.5, 2.0, 5.0, 4.5, 5.0]
[4.0, 3.0, 4.0, 4.0, 5.0]
815 +        userId  movieId  rating
73747     815        1     4.5
73748     815        2     3.0
73922     815      296     5.0
74362     815     1274     3.0
74678     815     1968     4.5
   movieId                title  rating
0        1            Toy Story     3.5
1        2              Jumanji     2.0
2      296         Pulp Fiction     5.0
3     1274                Akira     4.5
4     1968  Breakfast Club, The     5.0
++++ 5
[3.5, 2.0, 5.0, 4.5, 5.0]
[4.5, 3.0, 5.0, 3.0, 4.5]
1040 +        userId  movieId  rating
96689    1040        1     3.0
96690    1040        2     1.5
96733    1040      296     3.5
96859    1040     1274     3.0
96922    1040     1968     4.0
   movieId                title  rating
0        1            Toy Story     3.5
1        2              Jumanji     2.0
2      296         Pulp Fiction     5.0
3     1274                Akira     4.5
4     1968  Breakfast Club, The     5.0
++++ 5
[3.5, 2.0, 5.0, 4.5, 5.0]
[3.0, 1.5, 3.5, 3.0, 4.0]
1130 +         userId  movieId  rating
104167    1130        1     0.5
104168    1130        2     4.0
104214    1130      296     4.0
104363    1130     1274     4.5
104443    1130     1968     4.5
   movieId                title  rating
0        1            Toy Story     3.5
1        2              Jumanji     2.0
2      296         Pulp Fiction     5.0
3     1274                Akira     4.5
4     1968  Breakfast Club, The     5.0
++++ 5
[3.5, 2.0, 5.0, 4.5, 5.0]
[0.5, 4.0, 4.0, 4.5, 4.5]
1502 +         userId  movieId  rating
133876    1502        1     4.0
133877    1502        2     3.5
133917    1502      296     5.0
134058    1502     1274     4.0
134133    1502     1968     5.0
   movieId                title  rating
0        1            Toy Story     3.5
1        2              Jumanji     2.0
2      296         Pulp Fiction     5.0
3     1274                Akira     4.5
4     1968  Breakfast Club, The     5.0
++++ 5
[3.5, 2.0, 5.0, 4.5, 5.0]
[4.0, 3.5, 5.0, 4.0, 5.0]
1599 +         userId  movieId  rating
142722    1599        1     4.0
142723    1599        2     4.0
142810    1599      296     5.0
143068    1599     1274     4.0
143220    1599     1968     4.0
   movieId                title  rating
0        1            Toy Story     3.5
1        2              Jumanji     2.0
2      296         Pulp Fiction     5.0
3     1274                Akira     4.5
4     1968  Breakfast Club, The     5.0
++++ 5
[3.5, 2.0, 5.0, 4.5, 5.0]
[4.0, 4.0, 5.0, 4.0, 4.0]
1625 +         userId  movieId  rating
146811    1625        1     4.0
146812    1625        2     3.5
146867    1625      296     5.0
147011    1625     1274     4.0
147107    1625     1968     4.0
   movieId                title  rating
0        1            Toy Story     3.5
1        2              Jumanji     2.0
2      296         Pulp Fiction     5.0
3     1274                Akira     4.5
4     1968  Breakfast Club, The     5.0
++++ 5
[3.5, 2.0, 5.0, 4.5, 5.0]
[4.0, 3.5, 5.0, 4.0, 4.0]
1950 +         userId  movieId  rating
176143    1950        1     5.0
176144    1950        2     4.0
176186    1950      296     5.0
176349    1950     1274     4.0
176444    1950     1968     4.0
   movieId                title  rating
0        1            Toy Story     3.5
1        2              Jumanji     2.0
2      296         Pulp Fiction     5.0
3     1274                Akira     4.5
4     1968  Breakfast Club, The     5.0
++++ 5
[3.5, 2.0, 5.0, 4.5, 5.0]
[5.0, 4.0, 5.0, 4.0, 4.0]
2065 +         userId  movieId  rating
185283    2065        1     3.0
185284    2065        2     3.0
185340    2065      296     4.0
185472    2065     1274     3.0
185575    2065     1968     3.0
   movieId                title  rating
0        1            Toy Story     3.5
1        2              Jumanji     2.0
2      296         Pulp Fiction     5.0
3     1274                Akira     4.5
4     1968  Breakfast Club, The     5.0
++++ 5
[3.5, 2.0, 5.0, 4.5, 5.0]
[3.0, 3.0, 4.0, 3.0, 3.0]
2128 +         userId  movieId  rating
191789    2128        1     3.0
191790    2128        2     4.0
191830    2128      296     4.5
191932    2128     1274     5.0
191979    2128     1968     5.0
   movieId                title  rating
0        1            Toy Story     3.5
1        2              Jumanji     2.0
2      296         Pulp Fiction     5.0
3     1274                Akira     4.5
4     1968  Breakfast Club, The     5.0
++++ 5
[3.5, 2.0, 5.0, 4.5, 5.0]
[3.0, 4.0, 4.5, 5.0, 5.0]
2432 +         userId  movieId  rating
221536    2432        1     3.0
221537    2432        2     3.0
221593    2432      296     4.0
221842    2432     1274     2.0
222002    2432     1968     3.0
   movieId                title  rating
0        1            Toy Story     3.5
1        2              Jumanji     2.0
2      296         Pulp Fiction     5.0
3     1274                Akira     4.5
4     1968  Breakfast Club, The     5.0
++++ 5
[3.5, 2.0, 5.0, 4.5, 5.0]
[3.0, 3.0, 4.0, 2.0, 3.0]
2791 +         userId  movieId  rating
254324    2791        1     4.5
254325    2791        2     3.0
254344    2791      296     4.5
254446    2791     1274     4.5
254493    2791     1968     4.5
   movieId                title  rating
0        1            Toy Story     3.5
1        2              Jumanji     2.0
2      296         Pulp Fiction     5.0
3     1274                Akira     4.5
4     1968  Breakfast Club, The     5.0
++++ 5
[3.5, 2.0, 5.0, 4.5, 5.0]
[4.5, 3.0, 4.5, 4.5, 4.5]
2839 +         userId  movieId  rating
259233    2839        1     4.0
259234    2839        2     3.0
259292    2839      296     5.0
259427    2839     1274     5.0
259523    2839     1968     4.0
   movieId                title  rating
0        1            Toy Story     3.5
1        2              Jumanji     2.0
2      296         Pulp Fiction     5.0
3     1274                Akira     4.5
4     1968  Breakfast Club, The     5.0
++++ 5
[3.5, 2.0, 5.0, 4.5, 5.0]
[4.0, 3.0, 5.0, 5.0, 4.0]
2948 +         userId  movieId  rating
269447    2948        1     4.0
269448    2948        2     3.0
269502    2948      296     4.0
269603    2948     1274     3.0
269675    2948     1968     2.0
   movieId                title  rating
0        1            Toy Story     3.5
1        2              Jumanji     2.0
2      296         Pulp Fiction     5.0
3     1274                Akira     4.5
4     1968  Breakfast Club, The     5.0
++++ 5
[3.5, 2.0, 5.0, 4.5, 5.0]
[4.0, 3.0, 4.0, 3.0, 2.0]
3025 +         userId  movieId  rating
278199    3025        1     3.0
278200    3025        2     3.5
278255    3025      296     4.5
278410    3025     1274     3.0
278499    3025     1968     4.0
   movieId                title  rating
0        1            Toy Story     3.5
1        2              Jumanji     2.0
2      296         Pulp Fiction     5.0
3     1274                Akira     4.5
4     1968  Breakfast Club, The     5.0
++++ 5
[3.5, 2.0, 5.0, 4.5, 5.0]
[3.0, 3.5, 4.5, 3.0, 4.0]
3040 +         userId  movieId  rating
280209    3040        1     4.0
280210    3040        2     4.0
280221    3040      296     5.0
280282    3040     1274     5.0
280313    3040     1968     5.0
   movieId                title  rating
0        1            Toy Story     3.5
1        2              Jumanji     2.0
2      296         Pulp Fiction     5.0
3     1274                Akira     4.5
4     1968  Breakfast Club, The     5.0
++++ 5
[3.5, 2.0, 5.0, 4.5, 5.0]
[4.0, 4.0, 5.0, 5.0, 5.0]
3186 +         userId  movieId  rating
293305    3186        1     2.5
293306    3186        2     2.0
293361    3186      296     4.5
293562    3186     1274     2.0
293680    3186     1968     3.5
   movieId                title  rating
0        1            Toy Story     3.5
1        2              Jumanji     2.0
2      296         Pulp Fiction     5.0
3     1274                Akira     4.5
4     1968  Breakfast Club, The     5.0
++++ 5
[3.5, 2.0, 5.0, 4.5, 5.0]
[2.5, 2.0, 4.5, 2.0, 3.5]
3271 +         userId  movieId  rating
299824    3271        1     3.5
299825    3271        2     3.0
299876    3271      296     4.5
300015    3271     1274     2.0
300084    3271     1968     3.5
   movieId                title  rating
0        1            Toy Story     3.5
1        2              Jumanji     2.0
2      296         Pulp Fiction     5.0
3     1274                Akira     4.5
4     1968  Breakfast Club, The     5.0
++++ 5
[3.5, 2.0, 5.0, 4.5, 5.0]
[3.5, 3.0, 4.5, 2.0, 3.5]
3429 +         userId  movieId  rating
316845    3429        1     4.0
316846    3429        2     3.0
316876    3429      296     3.0
316948    3429     1274     4.0
317009    3429     1968     3.0
   movieId                title  rating
0        1            Toy Story     3.5
1        2              Jumanji     2.0
2      296         Pulp Fiction     5.0
3     1274                Akira     4.5
4     1968  Breakfast Club, The     5.0
++++ 5
[3.5, 2.0, 5.0, 4.5, 5.0]
[4.0, 3.0, 3.0, 4.0, 3.0]
3734 +         userId  movieId  rating
340015    3734        1     5.0
340016    3734        2     4.0
340087    3734      296     2.0
340315    3734     1274     5.0
340465    3734     1968     5.0
   movieId                title  rating
0        1            Toy Story     3.5
1        2              Jumanji     2.0
2      296         Pulp Fiction     5.0
3     1274                Akira     4.5
4     1968  Breakfast Club, The     5.0
++++ 5
[3.5, 2.0, 5.0, 4.5, 5.0]
[5.0, 4.0, 2.0, 5.0, 5.0]
4099 +         userId  movieId  rating
375223    4099        1     5.0
375224    4099        2     3.0
375288    4099      296     3.0
375504    4099     1274     3.5
375651    4099     1968     4.0
   movieId                title  rating
0        1            Toy Story     3.5
1        2              Jumanji     2.0
2      296         Pulp Fiction     5.0
3     1274                Akira     4.5
4     1968  Breakfast Club, The     5.0
++++ 5
[3.5, 2.0, 5.0, 4.5, 5.0]
[5.0, 3.0, 3.0, 3.5, 4.0]
4208 +         userId  movieId  rating
387004    4208        1     4.0
387005    4208        2     2.0
387119    4208      296     2.0
387377    4208     1274     3.0
387575    4208     1968     4.0
   movieId                title  rating
0        1            Toy Story     3.5
1        2              Jumanji     2.0
2      296         Pulp Fiction     5.0
3     1274                Akira     4.5
4     1968  Breakfast Club, The     5.0
++++ 5
[3.5, 2.0, 5.0, 4.5, 5.0]
[4.0, 2.0, 2.0, 3.0, 4.0]
4282 +         userId  movieId  rating
397984    4282        1     4.0
397985    4282        2     4.0
398040    4282      296     4.0
398210    4282     1274     4.0
398336    4282     1968     3.5
   movieId                title  rating
0        1            Toy Story     3.5
1        2              Jumanji     2.0
2      296         Pulp Fiction     5.0
3     1274                Akira     4.5
4     1968  Breakfast Club, The     5.0
++++ 5
[3.5, 2.0, 5.0, 4.5, 5.0]
[4.0, 4.0, 4.0, 4.0, 3.5]
4292 +         userId  movieId  rating
400307    4292        1     3.5
400308    4292        2     3.0
400349    4292      296     4.5
400503    4292     1274     5.0
400587    4292     1968     3.5
   movieId                title  rating
0        1            Toy Story     3.5
1        2              Jumanji     2.0
2      296         Pulp Fiction     5.0
3     1274                Akira     4.5
4     1968  Breakfast Club, The     5.0
++++ 5
[3.5, 2.0, 5.0, 4.5, 5.0]
[3.5, 3.0, 4.5, 5.0, 3.5]
4415 +         userId  movieId  rating
408738    4415        1     4.5
408739    4415        2     3.5
408844    4415      296     5.0
409135    4415     1274     0.5
409343    4415     1968     3.0
   movieId                title  rating
0        1            Toy Story     3.5
1        2              Jumanji     2.0
2      296         Pulp Fiction     5.0
3     1274                Akira     4.5
4     1968  Breakfast Club, The     5.0
++++ 5
[3.5, 2.0, 5.0, 4.5, 5.0]
[4.5, 3.5, 5.0, 0.5, 3.0]
4586 +         userId  movieId  rating
426228    4586        1     4.5
426229    4586        2     5.0
426259    4586      296     3.5
426396    4586     1274     3.5
426466    4586     1968     4.0
   movieId                title  rating
0        1            Toy Story     3.5
1        2              Jumanji     2.0
2      296         Pulp Fiction     5.0
3     1274                Akira     4.5
4     1968  Breakfast Club, The     5.0
++++ 5
[3.5, 2.0, 5.0, 4.5, 5.0]
[4.5, 5.0, 3.5, 3.5, 4.0]
4725 +         userId  movieId  rating
439244    4725        1     5.0
439245    4725        2     4.0
439263    4725      296     4.0
439313    4725     1274     2.0
439349    4725     1968     5.0
   movieId                title  rating
0        1            Toy Story     3.5
1        2              Jumanji     2.0
2      296         Pulp Fiction     5.0
3     1274                Akira     4.5
4     1968  Breakfast Club, The     5.0
++++ 5
[3.5, 2.0, 5.0, 4.5, 5.0]
[5.0, 4.0, 4.0, 2.0, 5.0]
4818 +         userId  movieId  rating
449041    4818        1     4.0
449042    4818        2     2.0
449108    4818      296     5.0
449267    4818     1274     3.0
449371    4818     1968     2.5
   movieId                title  rating
0        1            Toy Story     3.5
1        2              Jumanji     2.0
2      296         Pulp Fiction     5.0
3     1274                Akira     4.5
4     1968  Breakfast Club, The     5.0
++++ 5
[3.5, 2.0, 5.0, 4.5, 5.0]
[4.0, 2.0, 5.0, 3.0, 2.5]
5104 +         userId  movieId  rating
475288    5104        1     2.0
475289    5104        2     0.5
475393    5104      296     5.0
475670    5104     1274     4.0
475873    5104     1968     2.0
   movieId                title  rating
0        1            Toy Story     3.5
1        2              Jumanji     2.0
2      296         Pulp Fiction     5.0
3     1274                Akira     4.5
4     1968  Breakfast Club, The     5.0
++++ 5
[3.5, 2.0, 5.0, 4.5, 5.0]
[2.0, 0.5, 5.0, 4.0, 2.0]
5165 +         userId  movieId  rating
483940    5165        1     4.0
483941    5165        2     4.0
483966    5165      296     3.5
484072    5165     1274     3.0
484124    5165     1968     4.0
   movieId                title  rating
0        1            Toy Story     3.5
1        2              Jumanji     2.0
2      296         Pulp Fiction     5.0
3     1274                Akira     4.5
4     1968  Breakfast Club, The     5.0
++++ 5
[3.5, 2.0, 5.0, 4.5, 5.0]
[4.0, 4.0, 3.5, 3.0, 4.0]
5547 +         userId  movieId  rating
513560    5547        1     4.0
513561    5547        2     3.5
513603    5547      296     4.5
513707    5547     1274     4.0
513767    5547     1968     3.0
   movieId                title  rating
0        1            Toy Story     3.5
1        2              Jumanji     2.0
2      296         Pulp Fiction     5.0
3     1274                Akira     4.5
4     1968  Breakfast Club, The     5.0
++++ 5
[3.5, 2.0, 5.0, 4.5, 5.0]
[4.0, 3.5, 4.5, 4.0, 3.0]
6082 +         userId  movieId  rating
561189    6082        1     3.5
561190    6082        2     3.0
561224    6082      296     4.0
561338    6082     1274     4.0
561406    6082     1968     1.5
   movieId                title  rating
0        1            Toy Story     3.5
1        2              Jumanji     2.0
2      296         Pulp Fiction     5.0
3     1274                Akira     4.5
4     1968  Breakfast Club, The     5.0
++++ 5
[3.5, 2.0, 5.0, 4.5, 5.0]
[3.5, 3.0, 4.0, 4.0, 1.5]
6207 +         userId  movieId  rating
575407    6207        1     3.5
575408    6207        2     2.0
575436    6207      296     5.0
575523    6207     1274     5.0
575565    6207     1968     4.5
   movieId                title  rating
0        1            Toy Story     3.5
1        2              Jumanji     2.0
2      296         Pulp Fiction     5.0
3     1274                Akira     4.5
4     1968  Breakfast Club, The     5.0
++++ 5
[3.5, 2.0, 5.0, 4.5, 5.0]
[3.5, 2.0, 5.0, 5.0, 4.5]
6366 +         userId  movieId  rating
594942    6366        1     2.0
594943    6366        2     2.5
594996    6366      296     4.0
595144    6366     1274     4.0
595217    6366     1968     3.0
   movieId                title  rating
0        1            Toy Story     3.5
1        2              Jumanji     2.0
2      296         Pulp Fiction     5.0
3     1274                Akira     4.5
4     1968  Breakfast Club, The     5.0
++++ 5
[3.5, 2.0, 5.0, 4.5, 5.0]
[2.0, 2.5, 4.0, 4.0, 3.0]
6482 +         userId  movieId  rating
605173    6482        1     5.0
605174    6482        2     3.0
605264    6482      296     3.0
605493    6482     1274     1.0
605691    6482     1968     5.0
   movieId                title  rating
0        1            Toy Story     3.5
1        2              Jumanji     2.0
2      296         Pulp Fiction     5.0
3     1274                Akira     4.5
4     1968  Breakfast Club, The     5.0
++++ 5
[3.5, 2.0, 5.0, 4.5, 5.0]
[5.0, 3.0, 3.0, 1.0, 5.0]
6530 +         userId  movieId  rating
611461    6530        1     3.5
611462    6530        2     4.0
611614    6530      296     4.0
611969    6530     1274     3.0
612202    6530     1968     3.5
   movieId                title  rating
0        1            Toy Story     3.5
1        2              Jumanji     2.0
2      296         Pulp Fiction     5.0
3     1274                Akira     4.5
4     1968  Breakfast Club, The     5.0
++++ 5
[3.5, 2.0, 5.0, 4.5, 5.0]
[3.5, 4.0, 4.0, 3.0, 3.5]
7235 +         userId  movieId  rating
668396    7235        1     2.5
668397    7235        2     1.0
668428    7235      296     5.0
668523    7235     1274     2.0
668575    7235     1968     2.5
   movieId                title  rating
0        1            Toy Story     3.5
1        2              Jumanji     2.0
2      296         Pulp Fiction     5.0
3     1274                Akira     4.5
4     1968  Breakfast Club, The     5.0
++++ 5
[3.5, 2.0, 5.0, 4.5, 5.0]
[2.5, 1.0, 5.0, 2.0, 2.5]
7403 +         userId  movieId  rating
682305    7403        1     4.0
682306    7403        2     4.0
682369    7403      296     4.5
682518    7403     1274     4.5
682597    7403     1968     3.5
   movieId                title  rating
0        1            Toy Story     3.5
1        2              Jumanji     2.0
2      296         Pulp Fiction     5.0
3     1274                Akira     4.5
4     1968  Breakfast Club, The     5.0
++++ 5
[3.5, 2.0, 5.0, 4.5, 5.0]
[4.0, 4.0, 4.5, 4.5, 3.5]
7641 +         userId  movieId  rating
705768    7641        1     3.0
705769    7641        2     2.0

In [72]:
pearsonCorrelationDict

{75: 0.8272781516947562,
 106: 0.5860090386731182,
 686: 0.8320502943378437,
 815: 0.5765566601970551,
 1040: 0.9434563530497265,
 1130: 0.2891574659831201,
 1502: 0.8770580193070299,
 1599: 0.4385290096535153,
 1625: 0.716114874039432,
 1950: 0.179028718509858,
 2065: 0.4385290096535153,
 2128: 0.5860090386731196,
 2432: 0.1386750490563073,
 2791: 0.8770580193070299,
 2839: 0.8204126541423674,
 2948: -0.11720180773462392,
 3025: 0.45124262819713973,
 3040: 0.89514359254929,
 3186: 0.6784622064861935,
 3271: 0.26989594817970664,
 3429: 0.0,
 3734: -0.15041420939904673,
 4099: 0.05860090386731196,
 4208: 0.29417420270727607,
 4282: -0.4385290096535115,
 4292: 0.6564386345361464,
 4415: -0.11183835382312353,
 4586: -0.9024852563942795,
 4725: -0.08006407690254357,
 4818: 0.4885967564883424,
 5104: 0.7674257668936507,
 5165: -0.4385290096535153,
 5547: 0.17200522903844556,
 6082: -0.04728779924109591,
 6207: 0.9615384615384616,
 6366: 0.6577935144802716,
 6482: 0.0,
 6530: -0.3516054232038709,
 7235: 0.6981407669689391,
 7403: 0.11720180773462363,
 7641: 0.7161148740394331,
 7996: 0.626600514784504,
 8008: -0.22562131409856986,
 8086: 0.6933752452815365,
 8245: 0.0,
 8572: 0.8600261451922278,
 8675: 0.5370861555295773,
 9101: -0.08600261451922278,
 9358: 0.692178738358485,
 9663: 0.193972725041952,
 9994: 0.5030272728659587,
 10248: -0.24806946917841693,
 10315: 0.537086155529574,
 10368: 0.4688072309384945,
 10607: 0.41602514716892186,
 10707: 0.9615384615384616,
 10863: 0.6020183016345595,
 11314: 0.8204126541423654,
 11399: 0.517260600111872,
 11769: 0.9376144618769914,
 11827: 0.4902903378454601,
 12069: 0.0,
 12120: 0.9292940047327363,
 12211: 0.8600261451922278,
 12325: 0.9616783115081544,
 12916: 0.5860090386731196,
 12921: 0.6611073566849309,
 13053: 0.9607689228305227,
 13142: 0.6016568375961863,
 13260: 0.7844645405527362,
 13366: 0.8951435925492911,
 13768: 0.8770580193070289,
 13888: 0.2508726030021272,
 13923: 0.3516054232038718,
 13934: 0.17200522903844556,
 14529: 0.7417901772340937,
 14551: 0.537086155529574,
 14588: 0.21926450482675766,
 14984: 0.716114874039432,
 15137: 0.5860090386731196,
 15157: 0.9035841064985974,
 15466: 0.7205766921228921,
 15670: 0.516015687115336,
 15834: 0.22562131409856986,
 16292: 0.6577935144802716,
 16456: 0.7161148740394331,
 16506: 0.5481612620668942,
 17246: 0.48038446141526137,
 17438: 0.7093169886164387,
 17501: 0.8168748513121271,
 17502: 0.8272781516947562,
 17666: 0.7689238340176859,
 17735: 0.7042381820123422,
 17742: 0.3922322702763681,
 17757: 0.64657575013984,
 17854: 0.537086155529574,
 17897: 0.8770580193070289,
 17944: 0.2713848825944774,
 18301: 0.29838119751643016,
 18509: 0.1322214713369862}

In [75]:
pearsonDF = pd.DataFrame.from_dict(pearsonCorrelationDict, orient='index')
pearsonDF.columns = ['similarityIndex']
pearsonDF['userId'] = pearsonDF.index
pearsonDF.index = range(len(pearsonDF))
pearsonDF.head()

   similarityIndex  userId
0         0.827278      75
1         0.586009     106
2         0.832050     686
3         0.576557     815
4         0.943456    1040

#### The top x similar users to input user

Now let's get the top 50 users that are most similar to the input.

In [79]:
topUsers=pearsonDF.sort_values(by='similarityIndex', ascending=False)[0:50]
topUsers.head()

    similarityIndex  userId
64         0.961678   12325
34         0.961538    6207
55         0.961538   10707
67         0.960769   13053
4          0.943456    1040

Now, let's start recommending movies to the input user.

#### Rating of selected users to all movies

We're going to do this by taking the weighted average of the ratings of the movies using the Pearson Correlation as the weight. But to do this, we first need to get the movies watched by the users in our **pearsonDF** from the ratings dataframe and then store their correlation in a new column called \_similarityIndex". This is achieved below by merging of these two tables.

In [78]:
topUsersRating=topUsers.merge(ratings_df, left_on='userId', right_on='userId', how='inner')
topUsersRating.head()

   similarityIndex  userId  movieId  rating
0         0.961678   12325        1     3.5
1         0.961678   12325        2     1.5
2         0.961678   12325        3     3.0
3         0.961678   12325        5     0.5
4         0.961678   12325        6     2.5

Now all we need to do is simply multiply the movie rating by its weight (The similarity index), then sum up the new ratings and divide it by the sum of the weights.

We can easily do this by simply multiplying two columns, then grouping up the dataframe by movieId and then dividing two columns:

It shows the idea of all similar users to candidate movies for the input user:

In [80]:
#Multiplies the similarity by the user's ratings
topUsersRating['weightedRating'] = topUsersRating['similarityIndex']*topUsersRating['rating']
topUsersRating.head()

   similarityIndex  userId  movieId  rating  weightedRating
0         0.961678   12325        1     3.5        3.365874
1         0.961678   12325        2     1.5        1.442517
2         0.961678   12325        3     3.0        2.885035
3         0.961678   12325        5     0.5        0.480839
4         0.961678   12325        6     2.5        2.404196

In [83]:
#Applies a sum to the topUsers after grouping it up by userId
tempTopUsersRating = topUsersRating.groupby('movieId').sum()[['similarityIndex','weightedRating']]
tempTopUsersRating.columns = ['sum_similarityIndex','sum_weightedRating']
tempTopUsersRating.head()

         sum_similarityIndex  sum_weightedRating
movieId
1                  38.376281          140.800834
2                  38.376281           96.656745
3                  10.253981           27.254477
4                   0.929294            2.787882
5                  11.723262           27.151751

In [84]:
#Creates an empty dataframe
recommendation_df = pd.DataFrame()
#Now we take the weighted average
recommendation_df['weighted average recommendation score'] = tempTopUsersRating['sum_weightedRating']/tempTopUsersRating['sum_similarityIndex']
recommendation_df['movieId'] = tempTopUsersRating.index
recommendation_df.head()

   weighted average recommendation score  movieId
1                               3.668955        1
2                               2.518658        2
3                               2.657941        3
4                               3.000000        4
5                               2.316058        5

Now let's sort it and see the top 20 movies that the algorithm recommended!

In [ ]:
recommendation_df = recommendation_df.sort_values(by='weighted average recommendation score', ascending=False)
recommendation_df.head(10)

In [ ]:
movies_df.loc[movies_df['movieId'].isin(recommendation_df.head(10)['movieId'].tolist())]